const Destinations = [
    {
        id: 1,
        name: 'Prague Castle',
        description: 'A historic castle complex, symbol of Czech heritage.',
        image: 'https://upload.wikimedia.org/wikipedia/commons/9/9b/Charles_Bridge_%28Karl%C5%AFv_most%29.jpg',
        rating: 4.9,
        bestTime: 'April to October',
    },
    {
        id: 2,
        name: 'Český Krumlov',
        description: 'A picturesque town with a stunning castle and medieval charm.',
        image: 'https://upload.wikimedia.org/wikipedia/commons/4/4c/Cesky_Krumlov.jpg',
        rating: 4.8,
        bestTime: 'May to September',
    },
    {
        id: 3,
        name: 'Karlštejn Castle',
        description: 'A Gothic castle built to protect the crown jewels.',
        image: 'https://upload.wikimedia.org/wikipedia/commons/3/37/Karl%C5%A1tejn_Castle.jpg',
        rating: 4.7,
        bestTime: 'April to October',
    },
    {
        id: 4,
        name: 'Kutná Hora - St. Barbara\'s Church',
        description: 'A UNESCO World Heritage Site and stunning Gothic cathedral.',
        image: 'https://upload.wikimedia.org/wikipedia/commons/d/df/Saint_Barbara_Church%2C_Kutn%C3%A1_Hora.jpg',
        rating: 4.6,
        bestTime: 'March to November',
    },
    {
        id: 5,
        name: 'Bohemian Switzerland National Park',
        description: 'Known for its dramatic sandstone formations and Pravčická Gate.',
        image: 'https://upload.wikimedia.org/wikipedia/commons/1/1d/Pravcicka_Brana_2010-2.jpg',
        rating: 4.9,
        bestTime: 'May to September',
    },
    {
        id: 6,
        name: 'Moravian Karst',
        description: 'A unique karst region with caves and underground rivers.',
        image: 'https://upload.wikimedia.org/wikipedia/commons/3/34/Macoca_abyss.jpg',
        rating: 4.8,
        bestTime: 'May to October',
    },
    {
        id: 7,
        name: 'Telč',
        description: 'A fairy-tale town with Renaissance and Baroque architecture.',
        image: 'https://upload.wikimedia.org/wikipedia/commons/5/57/Tel%C4%8D_Town_Square.JPG',
        rating: 4.6,
        bestTime: 'April to September',
    },
    {
        id: 8,
        name: 'Olomouc',
        description: 'A historical city with stunning architecture and vibrant squares.',
        image: 'https://upload.wikimedia.org/wikipedia/commons/f/f1/Olomouc_Holy_Trinity_Column_2.jpg',
        rating: 4.7,
        bestTime: 'March to October',
    },
    {
        id: 9,
        name: 'Adršpach-Teplice Rocks',
        description: 'A magical rock city with unique sandstone formations.',
        image: 'https://upload.wikimedia.org/wikipedia/commons/b/bf/Adrspach_Teplice_Rocks.jpg',
        rating: 4.9,
        bestTime: 'May to October',
    },
    {
        id: 10,
        name: 'Lednice-Valtice Cultural Landscape',
        description: 'A vast UNESCO landscape with castles and ornamental gardens.',
        image: 'https://upload.wikimedia.org/wikipedia/commons/d/db/Lednice_Castle.jpg',
        rating: 4.8,
        bestTime: 'April to October',
    },
    {
        id: 11,
        name: 'Pilsner Urquell Brewery',
        description: 'Discover the birthplace of Pilsner beer.',
        image: 'https://upload.wikimedia.org/wikipedia/commons/c/cb/Pilsner_Urquell_Brewery.jpg',
        rating: 4.6,
        bestTime: 'Year-round',
    },
    {
        id: 12,
        name: 'Šumava National Park',
        description: 'A pristine natural reserve with forests, lakes, and wildlife.',
        image: 'https://upload.wikimedia.org/wikipedia/commons/a/a4/Sumava.jpg',
        rating: 4.7,
        bestTime: 'June to September',
    },
    {
        id: 13,
        name: 'Třebíč Basilica of St. Procopius',
        description: 'A Romanesque-Gothic basilica and UNESCO World Heritage Site.',
        image: 'https://upload.wikimedia.org/wikipedia/commons/5/51/Basilika_Trebic.jpg',
        rating: 4.5,
        bestTime: 'May to October',
    },
];

export default Destinations;
