const Destinations = [
    {
        id: 1,
        name: 'Prague Castle',
        description: 'A historic castle complex, symbol of Czech heritage.',
        image: '/acce/prague-castle-fotolia-jpeg_header-142535.jpeg',
        rating: 4.9,
        bestTime: 'April to October',
    },
    {
        id: 2,
        name: 'Český Krumlov',
        description: 'A picturesque town with a stunning castle and medieval charm.',
        image: '/acce/dreamstime_xxl_151405329.jpg',
        rating: 4.8,
        bestTime: 'May to September',
        bookingLink: 'https://booking.com/cesky-krumlov',
    },
    {
        id: 3,
        name: 'Karlštejn Castle',
        description: 'A Gothic castle built to protect the crown jewels.',
        image: '/acce/karlstejn-town-03-czechia.jpg',
        rating: 4.7,
        bestTime: 'April to October',
    },
    {
        id: 4,
        name: 'Kutná Hora - St. Barbara\'s Church',
        description: 'A UNESCO World Heritage Site and stunning Gothic cathedral.',
        image: '/acce/karlstejn-town-03-czechia.jpg',
        rating: 4.6,
        bestTime: 'March to November',
    },
    {
        id: 5,
        name: 'Bohemian Switzerland National Park',
        description: 'Known for its dramatic sandstone formations and Pravčická Gate.',
        image: '/acce/karlstejn-town-03-czechia.jpg',
        rating: 4.9,
        bestTime: 'May to September',
    },
    {
        id: 6,
        name: 'Moravian Karst',
        description: 'A unique karst region with caves and underground rivers.',
        image: '/acce/karlstejn-town-03-czechia.jpg',
        rating: 4.8,
        bestTime: 'May to October',
    },
    {
        id: 7,
        name: 'Telč',
        description: 'A fairy-tale town with Renaissance and Baroque architecture.',
        image: '/acce/karlstejn-town-03-czechia.jpg',
        rating: 4.6,
        bestTime: 'April to September',
    },
    {
        id: 8,
        name: 'Olomouc',
        description: 'A historical city with stunning architecture and vibrant squares.',
        image: '/acce/karlstejn-town-03-czechia.jpg',
        rating: 4.7,
        bestTime: 'March to October',
    },
    {
        id: 9,
        name: 'Adršpach-Teplice Rocks',
        description: 'A magical rock city with unique sandstone formations.',
        image: '/acce/karlstejn-town-03-czechia.jpg',
        rating: 4.9,
        bestTime: 'May to October',
    },
    {
        id: 10,
        name: 'Lednice-Valtice Cultural Landscape',
        description: 'A vast UNESCO landscape with castles and ornamental gardens.',
        image: '/acce/karlstejn-town-03-czechia.jpg',
        rating: 4.8,
        bestTime: 'April to October',
    },
    {
        id: 11,
        name: 'Pilsner Urquell Brewery',
        description: 'Discover the birthplace of Pilsner beer.',
        image: '/acce/karlstejn-town-03-czechia.jpg',
        rating: 4.6,
        bestTime: 'Year-round',
    },
    {
        id: 12,
        name: 'Šumava National Park',
        description: 'A pristine natural reserve with forests, lakes, and wildlife.',
        image: '/acce/karlstejn-town-03-czechia.jpg',
        rating: 4.7,
        bestTime: 'June to September',
    },
    
];

export default Destinations;
